// Generated by CIRCT firtool-1.149.0
module Axi4LiteMac(
  input         clock,
                reset,
  input  [31:0] S_AXI_awaddr,
  input         S_AXI_awvalid,
  output        S_AXI_awready,
  input  [31:0] S_AXI_wdata,
  input  [3:0]  S_AXI_wstrb,
  input         S_AXI_wvalid,
  output        S_AXI_wready,
  output [1:0]  S_AXI_bresp,
  output        S_AXI_bvalid,
  input         S_AXI_bready,
  input  [31:0] S_AXI_araddr,
  input         S_AXI_arvalid,
  output        S_AXI_arready,
  output [31:0] S_AXI_rdata,
  output [1:0]  S_AXI_rresp,
  output        S_AXI_rvalid,
  input         S_AXI_rready
);

  reg         dutValidReg;
  wire        _dut_io_in_ready;
  wire        _dut_io_out_valid;
  wire [31:0] _dut_io_out_bits;
  reg         awHoldValidReg;
  reg  [31:0] awHoldAddrReg;
  reg         wHoldValidReg;
  reg  [31:0] wHoldDataReg;
  reg  [3:0]  wHoldStrbReg;
  reg         bvalidReg;
  reg  [1:0]  brespReg;
  reg         softResetPulseReg;
  reg  [7:0]  aReg;
  reg  [7:0]  bReg;
  reg         pushPendingReg;
  reg         lastReg;
  wire        S_AXI_awready_0 = ~awHoldValidReg & ~bvalidReg & ~pushPendingReg;
  wire        S_AXI_wready_0 = ~wHoldValidReg & ~bvalidReg & ~pushPendingReg;
  reg  [31:0] rdataReg;
  reg         rvalidReg;
  reg  [1:0]  rrespReg;
  reg  [31:0] dutDataReg;
  wire        _softResetPulseReg_T = awHoldAddrReg == 32'h0;
  wire        _GEN = awHoldAddrReg == 32'h20;
  wire        doWrite = awHoldValidReg & wHoldValidReg & ~bvalidReg;
  wire        awFire = S_AXI_awvalid & S_AXI_awready_0;
  wire        wFire = S_AXI_wvalid & S_AXI_wready_0;
  wire        _GEN_0 = awHoldAddrReg == 32'h10;
  wire        _GEN_1 = awHoldAddrReg == 32'h14;
  wire        _GEN_2 = ~dutValidReg & _dut_io_out_valid;
  wire        arFire = S_AXI_arvalid & ~rvalidReg;
  wire        _GEN_3 = S_AXI_araddr[19:0] == 20'h24;
  wire        _GEN_4 = S_AXI_araddr[19:0] == 20'h28;
  wire        _GEN_5 = ~(&wHoldStrbReg) | _GEN_0 | _GEN_1;
  always @(posedge clock) begin
    if (reset) begin
      awHoldValidReg <= 1'h0;
      wHoldValidReg <= 1'h0;
      bvalidReg <= 1'h0;
      brespReg <= 2'h0;
      softResetPulseReg <= 1'h0;
      pushPendingReg <= 1'h0;
      lastReg <= 1'h0;
      rvalidReg <= 1'h0;
      rrespReg <= 2'h0;
      dutValidReg <= 1'h0;
    end
    else begin
      awHoldValidReg <= ~doWrite & (awFire | awHoldValidReg);
      wHoldValidReg <= ~doWrite & (wFire | wHoldValidReg);
      bvalidReg <= ~(bvalidReg & S_AXI_bready) & (doWrite | bvalidReg);
      if (doWrite)
        brespReg <=
          (&wHoldStrbReg)
            ? {~(_GEN_0 | _GEN_1 | _GEN | _softResetPulseReg_T), 1'h0}
            : 2'h2;
      softResetPulseReg <= doWrite & _softResetPulseReg_T & (&wHoldStrbReg);
      pushPendingReg <=
        ~(pushPendingReg & _dut_io_in_ready)
        & (doWrite & ~_GEN_5 & _GEN | pushPendingReg);
      if (~doWrite | _GEN_5 | ~_GEN) begin
      end
      else
        lastReg <= wHoldDataReg[0];
      rvalidReg <= ~(rvalidReg & S_AXI_rready) & (arFire | rvalidReg);
      if (arFire)
        rrespReg <= {~(_GEN_3 | _GEN_4), 1'h0};
      dutValidReg <= ~(arFire & _GEN_3) & (_GEN_2 | dutValidReg);
    end
    if (awFire)
      awHoldAddrReg <= {12'h0, S_AXI_awaddr[19:0]};
    if (wFire) begin
      wHoldDataReg <= S_AXI_wdata;
      wHoldStrbReg <= S_AXI_wstrb;
    end
    if (doWrite & (&wHoldStrbReg) & _GEN_0)
      aReg <= wHoldDataReg[7:0];
    if (~doWrite | ~(&wHoldStrbReg) | _GEN_0 | ~_GEN_1) begin
    end
    else
      bReg <= wHoldDataReg[7:0];
    if (arFire) begin
      if (_GEN_3)
        rdataReg <= dutDataReg;
      else if (_GEN_4)
        rdataReg <= {31'h0, dutValidReg};
    end
    if (_GEN_2)
      dutDataReg <= _dut_io_out_bits;
  end // always @(posedge)
  Mac dut (
    .clock           (clock),
    .reset           (softResetPulseReg | reset),
    .io_in_ready     (_dut_io_in_ready),
    .io_in_valid     (pushPendingReg),
    .io_in_bits_a    (aReg),
    .io_in_bits_b    (bReg),
    .io_in_bits_last (lastReg),
    .io_out_ready    (~dutValidReg),
    .io_out_valid    (_dut_io_out_valid),
    .io_out_bits     (_dut_io_out_bits)
  );
  assign S_AXI_awready = S_AXI_awready_0;
  assign S_AXI_wready = S_AXI_wready_0;
  assign S_AXI_bresp = brespReg;
  assign S_AXI_bvalid = bvalidReg;
  assign S_AXI_arready = ~rvalidReg;
  assign S_AXI_rdata = rdataReg;
  assign S_AXI_rresp = rrespReg;
  assign S_AXI_rvalid = rvalidReg;
endmodule

