// Generated by CIRCT firtool-1.149.0
module Mac(
  input         clock,
                reset,
  output        io_in_ready,
  input         io_in_valid,
  input  [7:0]  io_in_bits_a,
                io_in_bits_b,
  input         io_in_bits_last,
                io_out_ready,
  output        io_out_valid,
  output [31:0] io_out_bits
);

  reg  [1:0]  state;
  reg  [7:0]  aReg;
  reg  [7:0]  bReg;
  reg         lastReg;
  reg  [31:0] accReg;
  wire        io_in_ready_0 = state == 2'h0;
  wire        io_out_valid_0 = state == 2'h2;
  wire        _GEN = io_in_ready_0 & io_in_valid;
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      lastReg <= 1'h0;
      accReg <= 32'h0;
    end
    else begin
      if (io_in_ready_0) begin
        if (_GEN)
          state <= 2'h1;
      end
      else if (state == 2'h1) begin
        state <= {lastReg, 1'h0};
        accReg <= accReg + {16'h0, {8'h0, aReg} * {8'h0, bReg}};
      end
      else if (io_out_valid_0 & io_out_ready) begin
        state <= 2'h0;
        accReg <= 32'h0;
      end
      if (_GEN)
        lastReg <= io_in_bits_last;
    end
    if (_GEN) begin
      aReg <= io_in_bits_a;
      bReg <= io_in_bits_b;
    end
  end // always @(posedge)
  assign io_in_ready = io_in_ready_0;
  assign io_out_valid = io_out_valid_0;
  assign io_out_bits = accReg;
endmodule

