SIM ?= icarus
TOPLEVEL_LANG = verilog
WAVES = 1
VERILOG_SOURCES = $(abspath ../../generated/arithmetic/Adder.sv)
COCOTB_TOPLEVEL = Adder
COCOTB_TEST_MODULES = AdderSim

include $(shell cocotb-config --makefiles)/Makefile.sim