// Generated by CIRCT firtool-1.138.0
module MulFullRawFN(
  input         io_a_isNaN,
                io_a_isInf,
                io_a_isZero,
                io_a_sign,
  input  [9:0]  io_a_sExp,
  input  [24:0] io_a_sig,
  input         io_b_isNaN,
                io_b_isInf,
                io_b_isZero,
                io_b_sign,
  input  [9:0]  io_b_sExp,
  input  [24:0] io_b_sig,
  output        io_invalidExc,
                io_rawOut_isNaN,
                io_rawOut_isInf,
                io_rawOut_isZero,
                io_rawOut_sign,
  output [9:0]  io_rawOut_sExp,
  output [47:0] io_rawOut_sig
);

  assign io_invalidExc =
    io_a_isNaN & ~(io_a_sig[22]) | io_b_isNaN & ~(io_b_sig[22]) | io_a_isInf & io_b_isZero
    | io_a_isZero & io_b_isInf;
  assign io_rawOut_isNaN = io_a_isNaN | io_b_isNaN;
  assign io_rawOut_isInf = io_a_isInf | io_b_isInf;
  assign io_rawOut_isZero = io_a_isZero | io_b_isZero;
  assign io_rawOut_sign = io_a_sign ^ io_b_sign;
  assign io_rawOut_sExp = io_a_sExp + io_b_sExp - 10'h100;
  assign io_rawOut_sig = {23'h0, io_a_sig} * {23'h0, io_b_sig};
endmodule

module MulRawFN(
  input         io_a_isNaN,
                io_a_isInf,
                io_a_isZero,
                io_a_sign,
  input  [9:0]  io_a_sExp,
  input  [24:0] io_a_sig,
  input         io_b_isNaN,
                io_b_isInf,
                io_b_isZero,
                io_b_sign,
  input  [9:0]  io_b_sExp,
  input  [24:0] io_b_sig,
  output        io_invalidExc,
                io_rawOut_isNaN,
                io_rawOut_isInf,
                io_rawOut_isZero,
                io_rawOut_sign,
  output [9:0]  io_rawOut_sExp,
  output [26:0] io_rawOut_sig
);

  wire [47:0] _mulFullRaw_io_rawOut_sig;
  MulFullRawFN mulFullRaw (
    .io_a_isNaN       (io_a_isNaN),
    .io_a_isInf       (io_a_isInf),
    .io_a_isZero      (io_a_isZero),
    .io_a_sign        (io_a_sign),
    .io_a_sExp        (io_a_sExp),
    .io_a_sig         (io_a_sig),
    .io_b_isNaN       (io_b_isNaN),
    .io_b_isInf       (io_b_isInf),
    .io_b_isZero      (io_b_isZero),
    .io_b_sign        (io_b_sign),
    .io_b_sExp        (io_b_sExp),
    .io_b_sig         (io_b_sig),
    .io_invalidExc    (io_invalidExc),
    .io_rawOut_isNaN  (io_rawOut_isNaN),
    .io_rawOut_isInf  (io_rawOut_isInf),
    .io_rawOut_isZero (io_rawOut_isZero),
    .io_rawOut_sign   (io_rawOut_sign),
    .io_rawOut_sExp   (io_rawOut_sExp),
    .io_rawOut_sig    (_mulFullRaw_io_rawOut_sig)
  );
  assign io_rawOut_sig =
    {_mulFullRaw_io_rawOut_sig[47:22], |(_mulFullRaw_io_rawOut_sig[21:0])};
endmodule

module RoundAnyRawFNToRecFN_ie8_is26_oe8_os24(
  input         io_invalidExc,
                io_in_isNaN,
                io_in_isInf,
                io_in_isZero,
                io_in_sign,
  input  [9:0]  io_in_sExp,
  input  [26:0] io_in_sig,
  output [32:0] io_out
);

  wire [8:0]  _roundMask_T_1 = ~(io_in_sExp[8:0]);
  wire [64:0] _GEN = {59'h0, _roundMask_T_1[5:0]};
  wire [64:0] roundMask_shift = $unsigned($signed(65'sh10000000000000000 >>> _GEN));
  wire [15:0] _roundMask_T_12 =
    {8'h0, roundMask_shift[57:50]} | {roundMask_shift[49:42], 8'h0};
  wire [15:0] _roundMask_T_22 =
    {4'h0, _roundMask_T_12[15:4] & 12'hF0F} | {_roundMask_T_12[11:0] & 12'hF0F, 4'h0};
  wire [15:0] _roundMask_T_32 =
    {2'h0, _roundMask_T_22[15:2] & 14'h3333} | {_roundMask_T_22[13:0] & 14'h3333, 2'h0};
  wire [64:0] roundMask_shift_1 = $unsigned($signed(65'sh10000000000000000 >>> _GEN));
  wire [24:0] _roundMask_T_73 =
    _roundMask_T_1[8]
      ? (_roundMask_T_1[7]
           ? {~(_roundMask_T_1[6]
                  ? 22'h0
                  : ~{{1'h0, _roundMask_T_32[15:1] & 15'h5555}
                        | {_roundMask_T_32[14:0] & 15'h5555, 1'h0},
                      roundMask_shift[58],
                      roundMask_shift[59],
                      roundMask_shift[60],
                      roundMask_shift[61],
                      roundMask_shift[62],
                      roundMask_shift[63]}),
              3'h7}
           : {22'h0,
              _roundMask_T_1[6]
                ? {roundMask_shift_1[0], roundMask_shift_1[1], roundMask_shift_1[2]}
                : 3'h0})
      : 25'h0;
  wire        _common_underflow_T_4 = _roundMask_T_73[0] | io_in_sig[26];
  wire [25:0] _GEN_0 = {_roundMask_T_73[24:1], _common_underflow_T_4, 1'h1};
  wire [25:0] _roundPosBit_T =
    io_in_sig[26:1] & {1'h1, ~(_roundMask_T_73[24:1]), ~_common_underflow_T_4} & _GEN_0;
  wire [25:0] roundedSig =
    (|_roundPosBit_T)
      ? {1'h0, io_in_sig[26:2] | {_roundMask_T_73[24:1], _common_underflow_T_4}} + 26'h1
        & ~((|_roundPosBit_T) & (io_in_sig[25:0] & _GEN_0) == 26'h0
              ? {_roundMask_T_73[24:1], _common_underflow_T_4, 1'h1}
              : 26'h0)
      : {1'h0, io_in_sig[26:2] & {~(_roundMask_T_73[24:1]), ~_common_underflow_T_4}};
  wire [10:0] sRoundedExp = {io_in_sExp[9], io_in_sExp} + {9'h0, roundedSig[25:24]};
  wire        common_totalUnderflow = $signed(sRoundedExp) < 11'sh6B;
  wire        isNaNOut = io_invalidExc | io_in_isNaN;
  wire        notNaN_isInfOut =
    io_in_isInf | ~isNaNOut & ~io_in_isInf & ~io_in_isZero
    & $signed(sRoundedExp[10:7]) > 4'sh2;
  assign io_out =
    {~isNaNOut & io_in_sign,
     sRoundedExp[8:0] & ~(io_in_isZero | common_totalUnderflow ? 9'h1C0 : 9'h0)
       & {2'h3, ~notNaN_isInfOut, 6'h3F} | (notNaN_isInfOut ? 9'h180 : 9'h0)
       | (isNaNOut ? 9'h1C0 : 9'h0),
     isNaNOut | io_in_isZero | common_totalUnderflow
       ? {isNaNOut, 22'h0}
       : io_in_sig[26] ? roundedSig[23:1] : roundedSig[22:0]};
endmodule

module RoundRawFNToRecFN_e8_s24(
  input         io_invalidExc,
                io_in_isNaN,
                io_in_isInf,
                io_in_isZero,
                io_in_sign,
  input  [9:0]  io_in_sExp,
  input  [26:0] io_in_sig,
  output [32:0] io_out
);

  RoundAnyRawFNToRecFN_ie8_is26_oe8_os24 roundAnyRawFNToRecFN (
    .io_invalidExc (io_invalidExc),
    .io_in_isNaN   (io_in_isNaN),
    .io_in_isInf   (io_in_isInf),
    .io_in_isZero  (io_in_isZero),
    .io_in_sign    (io_in_sign),
    .io_in_sExp    (io_in_sExp),
    .io_in_sig     (io_in_sig),
    .io_out        (io_out)
  );
endmodule

module MulRecFN(
  input  [32:0] io_a,
                io_b,
  output [32:0] io_out
);

  wire        _mulRawFN_io_invalidExc;
  wire        _mulRawFN_io_rawOut_isNaN;
  wire        _mulRawFN_io_rawOut_isInf;
  wire        _mulRawFN_io_rawOut_isZero;
  wire        _mulRawFN_io_rawOut_sign;
  wire [9:0]  _mulRawFN_io_rawOut_sExp;
  wire [26:0] _mulRawFN_io_rawOut_sig;
  MulRawFN mulRawFN (
    .io_a_isNaN       ((&(io_a[31:30])) & io_a[29]),
    .io_a_isInf       ((&(io_a[31:30])) & ~(io_a[29])),
    .io_a_isZero      (~(|(io_a[31:29]))),
    .io_a_sign        (io_a[32]),
    .io_a_sExp        ({1'h0, io_a[31:23]}),
    .io_a_sig         ({1'h0, |(io_a[31:29]), io_a[22:0]}),
    .io_b_isNaN       ((&(io_b[31:30])) & io_b[29]),
    .io_b_isInf       ((&(io_b[31:30])) & ~(io_b[29])),
    .io_b_isZero      (~(|(io_b[31:29]))),
    .io_b_sign        (io_b[32]),
    .io_b_sExp        ({1'h0, io_b[31:23]}),
    .io_b_sig         ({1'h0, |(io_b[31:29]), io_b[22:0]}),
    .io_invalidExc    (_mulRawFN_io_invalidExc),
    .io_rawOut_isNaN  (_mulRawFN_io_rawOut_isNaN),
    .io_rawOut_isInf  (_mulRawFN_io_rawOut_isInf),
    .io_rawOut_isZero (_mulRawFN_io_rawOut_isZero),
    .io_rawOut_sign   (_mulRawFN_io_rawOut_sign),
    .io_rawOut_sExp   (_mulRawFN_io_rawOut_sExp),
    .io_rawOut_sig    (_mulRawFN_io_rawOut_sig)
  );
  RoundRawFNToRecFN_e8_s24 roundRawFNToRecFN (
    .io_invalidExc (_mulRawFN_io_invalidExc),
    .io_in_isNaN   (_mulRawFN_io_rawOut_isNaN),
    .io_in_isInf   (_mulRawFN_io_rawOut_isInf),
    .io_in_isZero  (_mulRawFN_io_rawOut_isZero),
    .io_in_sign    (_mulRawFN_io_rawOut_sign),
    .io_in_sExp    (_mulRawFN_io_rawOut_sExp),
    .io_in_sig     (_mulRawFN_io_rawOut_sig),
    .io_out        (io_out)
  );
endmodule

module FPMUL_8_24(
  input         clock,
                reset,
  input  [31:0] io_in_a,
                io_in_b,
  output [31:0] io_out
);

  wire [32:0] _opRecFN_io_out;
  wire        opRecFN_io_a_rawIn_isZeroExpIn = io_in_a[30:23] == 8'h0;
  wire [4:0]  opRecFN_io_a_rawIn_normDist =
    io_in_a[22]
      ? 5'h0
      : io_in_a[21]
          ? 5'h1
          : io_in_a[20]
              ? 5'h2
              : io_in_a[19]
                  ? 5'h3
                  : io_in_a[18]
                      ? 5'h4
                      : io_in_a[17]
                          ? 5'h5
                          : io_in_a[16]
                              ? 5'h6
                              : io_in_a[15]
                                  ? 5'h7
                                  : io_in_a[14]
                                      ? 5'h8
                                      : io_in_a[13]
                                          ? 5'h9
                                          : io_in_a[12]
                                              ? 5'hA
                                              : io_in_a[11]
                                                  ? 5'hB
                                                  : io_in_a[10]
                                                      ? 5'hC
                                                      : io_in_a[9]
                                                          ? 5'hD
                                                          : io_in_a[8]
                                                              ? 5'hE
                                                              : io_in_a[7]
                                                                  ? 5'hF
                                                                  : io_in_a[6]
                                                                      ? 5'h10
                                                                      : io_in_a[5]
                                                                          ? 5'h11
                                                                          : io_in_a[4]
                                                                              ? 5'h12
                                                                              : io_in_a[3]
                                                                                  ? 5'h13
                                                                                  : io_in_a[2]
                                                                                      ? 5'h14
                                                                                      : io_in_a[1]
                                                                                          ? 5'h15
                                                                                          : 5'h16;
  wire [53:0] _opRecFN_io_a_rawIn_subnormFract_T =
    {31'h0, io_in_a[22:0]} << opRecFN_io_a_rawIn_normDist;
  wire [8:0]  _opRecFN_io_a_rawIn_adjustedExp_T_4 =
    (opRecFN_io_a_rawIn_isZeroExpIn
       ? {4'hF, ~opRecFN_io_a_rawIn_normDist}
       : {1'h0, io_in_a[30:23]}) + {7'h20, opRecFN_io_a_rawIn_isZeroExpIn ? 2'h2 : 2'h1};
  wire [2:0]  _opRecFN_io_a_T_1 =
    opRecFN_io_a_rawIn_isZeroExpIn & ~(|(io_in_a[22:0]))
      ? 3'h0
      : _opRecFN_io_a_rawIn_adjustedExp_T_4[8:6];
  wire        opRecFN_io_b_rawIn_isZeroExpIn = io_in_b[30:23] == 8'h0;
  wire [4:0]  opRecFN_io_b_rawIn_normDist =
    io_in_b[22]
      ? 5'h0
      : io_in_b[21]
          ? 5'h1
          : io_in_b[20]
              ? 5'h2
              : io_in_b[19]
                  ? 5'h3
                  : io_in_b[18]
                      ? 5'h4
                      : io_in_b[17]
                          ? 5'h5
                          : io_in_b[16]
                              ? 5'h6
                              : io_in_b[15]
                                  ? 5'h7
                                  : io_in_b[14]
                                      ? 5'h8
                                      : io_in_b[13]
                                          ? 5'h9
                                          : io_in_b[12]
                                              ? 5'hA
                                              : io_in_b[11]
                                                  ? 5'hB
                                                  : io_in_b[10]
                                                      ? 5'hC
                                                      : io_in_b[9]
                                                          ? 5'hD
                                                          : io_in_b[8]
                                                              ? 5'hE
                                                              : io_in_b[7]
                                                                  ? 5'hF
                                                                  : io_in_b[6]
                                                                      ? 5'h10
                                                                      : io_in_b[5]
                                                                          ? 5'h11
                                                                          : io_in_b[4]
                                                                              ? 5'h12
                                                                              : io_in_b[3]
                                                                                  ? 5'h13
                                                                                  : io_in_b[2]
                                                                                      ? 5'h14
                                                                                      : io_in_b[1]
                                                                                          ? 5'h15
                                                                                          : 5'h16;
  wire [53:0] _opRecFN_io_b_rawIn_subnormFract_T =
    {31'h0, io_in_b[22:0]} << opRecFN_io_b_rawIn_normDist;
  wire [8:0]  _opRecFN_io_b_rawIn_adjustedExp_T_4 =
    (opRecFN_io_b_rawIn_isZeroExpIn
       ? {4'hF, ~opRecFN_io_b_rawIn_normDist}
       : {1'h0, io_in_b[30:23]}) + {7'h20, opRecFN_io_b_rawIn_isZeroExpIn ? 2'h2 : 2'h1};
  wire [2:0]  _opRecFN_io_b_T_1 =
    opRecFN_io_b_rawIn_isZeroExpIn & ~(|(io_in_b[22:0]))
      ? 3'h0
      : _opRecFN_io_b_rawIn_adjustedExp_T_4[8:6];
  wire        io_out_rawIn_isInf = (&(_opRecFN_io_out[31:30])) & ~(_opRecFN_io_out[29]);
  wire        io_out_isSubnormal = $signed({1'h0, _opRecFN_io_out[31:23]}) < 10'sh82;
  wire [23:0] _io_out_denormFract_T_1 =
    {1'h0, |(_opRecFN_io_out[31:29]), _opRecFN_io_out[22:1]} >> 5'h1
    - _opRecFN_io_out[27:23];
  MulRecFN opRecFN (
    .io_a
      ({io_in_a[31],
        _opRecFN_io_a_T_1[2:1],
        _opRecFN_io_a_T_1[0] | (&(_opRecFN_io_a_rawIn_adjustedExp_T_4[8:7]))
          & (|(io_in_a[22:0])),
        _opRecFN_io_a_rawIn_adjustedExp_T_4[5:0],
        opRecFN_io_a_rawIn_isZeroExpIn
          ? {_opRecFN_io_a_rawIn_subnormFract_T[21:0], 1'h0}
          : io_in_a[22:0]}),
    .io_b
      ({io_in_b[31],
        _opRecFN_io_b_T_1[2:1],
        _opRecFN_io_b_T_1[0] | (&(_opRecFN_io_b_rawIn_adjustedExp_T_4[8:7]))
          & (|(io_in_b[22:0])),
        _opRecFN_io_b_rawIn_adjustedExp_T_4[5:0],
        opRecFN_io_b_rawIn_isZeroExpIn
          ? {_opRecFN_io_b_rawIn_subnormFract_T[21:0], 1'h0}
          : io_in_b[22:0]}),
    .io_out (_opRecFN_io_out)
  );
  assign io_out =
    {_opRecFN_io_out[32],
     (io_out_isSubnormal ? 8'h0 : _opRecFN_io_out[30:23] + 8'h7F)
       | {8{(&(_opRecFN_io_out[31:30])) & _opRecFN_io_out[29] | io_out_rawIn_isInf}},
     io_out_isSubnormal
       ? _io_out_denormFract_T_1[22:0]
       : io_out_rawIn_isInf ? 23'h0 : _opRecFN_io_out[22:0]};
endmodule


// ----- 8< ----- FILE "verification/layers-FPMUL_8_24-Verification.sv" ----- 8< -----

// Generated by CIRCT firtool-1.138.0
`ifndef layers_FPMUL_8_24_Verification
  `define layers_FPMUL_8_24_Verification
`endif // not def layers_FPMUL_8_24_Verification

// ----- 8< ----- FILE "verification/assert/layers-FPMUL_8_24-Verification-Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.138.0
`ifndef layers_FPMUL_8_24_Verification_Assert
  `define layers_FPMUL_8_24_Verification_Assert
  `include "layers-FPMUL_8_24-Verification.sv"
`endif // not def layers_FPMUL_8_24_Verification_Assert

// ----- 8< ----- FILE "verification/assume/layers-FPMUL_8_24-Verification-Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.138.0
`ifndef layers_FPMUL_8_24_Verification_Assume
  `define layers_FPMUL_8_24_Verification_Assume
  `include "layers-FPMUL_8_24-Verification.sv"
`endif // not def layers_FPMUL_8_24_Verification_Assume

// ----- 8< ----- FILE "verification/cover/layers-FPMUL_8_24-Verification-Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.138.0
`ifndef layers_FPMUL_8_24_Verification_Cover
  `define layers_FPMUL_8_24_Verification_Cover
  `include "layers-FPMUL_8_24-Verification.sv"
`endif // not def layers_FPMUL_8_24_Verification_Cover
