// generated by tempo -- do not edit
module tempo_top(
  input clock,
  input [31:0] S_AXI_awaddr,
  input S_AXI_awvalid,
  input [31:0] S_AXI_wdata,
  input [3:0] S_AXI_wstrb,
  input S_AXI_wvalid,
  input S_AXI_bready,
  input [31:0] S_AXI_araddr,
  input S_AXI_arvalid,
  input S_AXI_rready
);
  reg [15:0] t = 16'd0;
  always @(posedge clock) t <= t + 16'd1;
  wire rst = (t == 16'd0);
  wire S_AXI_awready;
  wire S_AXI_wready;
  wire [1:0] S_AXI_bresp;
  wire S_AXI_bvalid;
  wire S_AXI_arready;
  wire [31:0] S_AXI_rdata;
  wire [1:0] S_AXI_rresp;
  wire S_AXI_rvalid;
  Axi4LiteMac dut(.clock(clock), .reset(rst), .S_AXI_awaddr(S_AXI_awaddr), .S_AXI_awvalid(S_AXI_awvalid), .S_AXI_wdata(S_AXI_wdata), .S_AXI_wstrb(S_AXI_wstrb), .S_AXI_wvalid(S_AXI_wvalid), .S_AXI_bready(S_AXI_bready), .S_AXI_araddr(S_AXI_araddr), .S_AXI_arvalid(S_AXI_arvalid), .S_AXI_rready(S_AXI_rready), .S_AXI_awready(S_AXI_awready), .S_AXI_wready(S_AXI_wready), .S_AXI_bresp(S_AXI_bresp), .S_AXI_bvalid(S_AXI_bvalid), .S_AXI_arready(S_AXI_arready), .S_AXI_rdata(S_AXI_rdata), .S_AXI_rresp(S_AXI_rresp), .S_AXI_rvalid(S_AXI_rvalid));
  tempo_monitor mon(.clock(clock), .dis(rst), .S_AXI_awaddr(S_AXI_awaddr), .S_AXI_awvalid(S_AXI_awvalid), .S_AXI_awready(S_AXI_awready), .S_AXI_wdata(S_AXI_wdata), .S_AXI_wstrb(S_AXI_wstrb), .S_AXI_wvalid(S_AXI_wvalid), .S_AXI_wready(S_AXI_wready), .S_AXI_bresp(S_AXI_bresp), .S_AXI_bvalid(S_AXI_bvalid), .S_AXI_bready(S_AXI_bready), .S_AXI_araddr(S_AXI_araddr), .S_AXI_arvalid(S_AXI_arvalid), .S_AXI_arready(S_AXI_arready), .S_AXI_rdata(S_AXI_rdata), .S_AXI_rresp(S_AXI_rresp), .S_AXI_rvalid(S_AXI_rvalid), .S_AXI_rready(S_AXI_rready));
endmodule
