// Generated by CIRCT firtool-1.149.0
module Adder(
  input        clock,
               reset,
  input  [7:0] io_a,
               io_b,
  output [8:0] io_s
);

  wire [8:0] io_s_0 = {1'h0, io_a} + {1'h0, io_b};
  reg        hasBeenResetReg;
  initial
    hasBeenResetReg = 1'bx;
  always @(posedge clock) begin
    if (reset)
      hasBeenResetReg <= 1'h1;
  end // always @(posedge)
  wire       _GEN = ~(hasBeenResetReg === 1'h1 & reset === 1'h0);
  assert property (io_a + io_b == io_s);
  assign io_s = io_s_0;
endmodule

